# Generated by Django 5.2 on 2025-06-11 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DarajaCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumerKey', models.CharField(max_length=255)),
                ('consumerSecret', models.CharField(max_length=255)),
                ('shortcode', models.CharField(max_length=20)),
                ('passkey', models.CharField(max_length=255)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=20)),
                ('serviceType', models.CharField(choices=[('c2b', 'C2B'), ('b2c', 'B2C'), ('b2b', 'B2B')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daraja_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
