# Generated by Django 5.2 on 2025-05-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0003_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
