# Generated by Django 5.2 on 2025-05-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='access_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
