# Generated by Django 5.2 on 2025-05-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_integration', '0002_payment_access_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
